basePath: /api/v1
definitions:
  handlers.CreateCatalogDefinitionRequest:
    properties:
      parser:
        $ref: '#/definitions/handlers.ParserCatalogDefinitionRequest'
      scraper:
        $ref: '#/definitions/handlers.ScraperCatalogDefinitionRequest'
    type: object
  handlers.CreateCatalogScraperRequest:
    properties:
      cron:
        type: string
      urls:
        items:
          type: string
        type: array
    type: object
  handlers.CreateProductRequest:
    properties:
      name:
        type: string
      websites:
        items:
          type: string
        type: array
    type: object
  handlers.CreateProductResponse:
    properties:
      id:
        type: string
    type: object
  handlers.CreateWebsiteRequest:
    properties:
      host:
        type: string
      name:
        type: string
    type: object
  handlers.CreateWebsiteResponse:
    properties:
      id:
        type: string
    type: object
  handlers.FieldDefinitionRequest:
    properties:
      displayName:
        type: string
      identifier:
        type: string
      required:
        type: boolean
      selector:
        type: string
    type: object
  handlers.PaginationDefinitionRequest:
    properties:
      maxPage:
        type: integer
      pageNumberParamName:
        type: string
    type: object
  handlers.ParserCatalogDefinitionRequest:
    properties:
      fields:
        items:
          $ref: '#/definitions/handlers.FieldDefinitionRequest'
        type: array
    type: object
  handlers.ScraperCatalogDefinitionRequest:
    properties:
      contentSelector:
        type: string
      pagination:
        $ref: '#/definitions/handlers.PaginationDefinitionRequest'
    type: object
info:
  contact: {}
  description: This is a sample server for iTracker API.
  title: iTracker API
  version: "1.0"
paths:
  /products:
    post:
      consumes:
      - application/json
      operationId: create-product
      parameters:
      - description: CreateProductRequest
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.CreateProductResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new product
      tags:
      - Products
  /websites:
    post:
      consumes:
      - application/json
      operationId: create-website
      parameters:
      - description: CreateWebsiteRequest
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateWebsiteRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.CreateWebsiteResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new website
      tags:
      - Websites
  /websites/{id}/catalog/definitions:
    post:
      consumes:
      - application/json
      operationId: create-catalog-definition
      parameters:
      - description: Website ID
        in: path
        name: id
        required: true
        type: string
      - description: CreateCatalogDefinitionRequest
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateCatalogDefinitionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new catalog scraper definition for website
      tags:
      - Websites
  /websites/{id}/catalog/definitions/{definitionId}/scrapers:
    post:
      consumes:
      - application/json
      operationId: create-catalog-definition-scraper
      parameters:
      - description: Website ID
        in: path
        name: id
        required: true
        type: string
      - description: Catalog Definition ID
        in: path
        name: definitionId
        required: true
        type: string
      - description: CreateCatalogScraperRequest
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateCatalogScraperRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new scraper for website definition
      tags:
      - Websites
swagger: "2.0"
