basePath: /api/v1
definitions:
  handlers.CreateProductRequest:
    properties:
      name:
        type: string
      websites:
        items:
          type: string
        type: array
    type: object
  handlers.CreateProductResponse:
    properties:
      id:
        type: string
    type: object
  handlers.CreateWebsiteRequest:
    properties:
      name:
        type: string
      url:
        type: string
    type: object
  handlers.CreateWebsiteResponse:
    properties:
      id:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server for iTracker API.
  title: iTracker API
  version: "1.0"
paths:
  /products:
    post:
      consumes:
      - application/json
      operationId: create-product
      parameters:
      - description: CreateProductRequest
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.CreateProductResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new product
      tags:
      - Products
  /websites:
    post:
      consumes:
      - application/json
      operationId: create-website
      parameters:
      - description: CreateWebsiteRequest
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateWebsiteRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.CreateWebsiteResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new website
      tags:
      - Websites
swagger: "2.0"
